services:
  identityserver.host:
    image: identityserver.host
    build:
      context: .
      dockerfile: IdentityServer.Host/Dockerfile
    ports:
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      acme:
        aliases:
          - login.acme.local
  bff.sample:
    image: bff.sample
    build:
      context: .
      dockerfile: Bff.Sample/Dockerfile
    ports:
      - "5002:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - identityserver.host
    networks:
      acme:
        aliases:
          - app.acme.local
networks:
  acme:
    driver: bridge