services:
  identityserver.host:
    image: identityserver.host
    build:
      context: .
      dockerfile: IdentityServer.Host/Dockerfile
    networks:
      acme:
        aliases:
          - login.acme.local
  bff.sample:
    image: bff.sample
    build:
      context: .
      dockerfile: Bff.Sample/Dockerfile
    depends_on:
      - identityserver.host
    networks:
      acme:
        aliases:
          - app.acme.local
networks:
  acme:
    driver: bridge